---
title: "Passion Driven Statistics"
author: "Erik B. Erhardt, Alan T. Arnholt, Lisa Dierker, and others"
date: "Modified for use with [R](https://www.r-project.org/) and [Zotero](https://www.zotero.org/)"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book
css: "./CSS/style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, fig.align = "center", comment = NA, warning = FALSE, message = FALSE)
```

<<<<<<< HEAD
# 0 Foreward {-}
=======
# Foreward {-}
>>>>>>> dd03d8d5450fd3972c58d080b1e267082d55819d

Follow your passion through statistics while learning the R language.

**Video:  00. Passion-Driven Statistics** in 2 minutes
<iframe src="https://player.vimeo.com/video/159566845?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>


Statistical analysis is arguably the most salient point of intersection among
diverse disciplines, yet developing analytic skills is often viewed as an
obstacle rather than an opportunity to pursue your own interests and to answer
questions that you feel passionately about.

This is why we created **[Passion-Driven Statistics](https://passiondrivenstatistics.com/)**. It is statistics in the
<<<<<<< HEAD
service of *your own research* --- in the service of *your passion*. It is a
=======
service of your own research --- in the service of your passion. It is a
>>>>>>> dd03d8d5450fd3972c58d080b1e267082d55819d
multidisciplinary, project-based curriculum that supports students in
conducting original research, asking original questions, and communicating
methods and results using the language of statistics. The curriculum supports
students to work with existing data covering health, geography and earth
science, government, business, education, genetics, and more. From existing
data, you'll be able to pose questions of interest to you and then use
statistical software (e.g., R) to turn raw data into useful information.

We believe that students from diverse educational, social and economic
backgrounds deserve not only a seat in a classroom, but also a welcoming place
at the table. Our goal is to increase the number and diversity of students
exposed to meaningful and empowering data analysis experiences and to inspire
the pursuit of advanced data-driven experiences and opportunities for everyone!

<!---
was in title: "[GitHub,](https://github.com/) and"
## Copyright {-}
-->

```{block, type = "rmdlicense"}
This work is licensed under [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License]( http://creativecommons.org/licenses/by-nc-sa/3.0)

Please report any mistakes/typos/errata, suggestions, or problems at <https://github.com/erikerhardt/PDS-Bookdown2/issues>.

The source code that creates this document resides at <https://github.com/erikerhardt/PDS-Bookdown2>, derived from <https://github.com/alanarnholt/PDS-Bookdown2/>.
```

This document is maintained by [Erik B. Erhardt](https://statacumen.com/about/)
  for use in a special version of UNM Stat 145: **[Statistics for Research (S4R)](https://statacumen.com/teaching/s4r-s19/)**.


Last updated: `r format(Sys.time(), "%B %d, %Y")`

<!---
-->

<!---
Video links:  https://passiondrivenstatistics.com/r/

**Video:  00. Passion-Driven Statistics**
<iframe src="https://player.vimeo.com/video/159566845?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
<<<<<<< HEAD
original page size: <iframe src="https://player.vimeo.com/video/159566845?title=0&amp;byline=0&amp;portrait=0" width="1165" height="655" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
=======
<iframe src="https://player.vimeo.com/video/159566845?title=0&amp;byline=0&amp;portrait=0" width="1165" height="655" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
>>>>>>> dd03d8d5450fd3972c58d080b1e267082d55819d

**Video:  01. Introduction**
<iframe src="https://www.youtube.com/embed/_8A0zx51BKs?rel=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  02. Data Sets and Code Books**
<iframe src="https://player.vimeo.com/video/129601017?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  03. Literature Review**
<iframe src="https://player.vimeo.com/video/139525602?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  04. Working with Data**
<iframe src="https://player.vimeo.com/video/157497682?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  05. Data Management**
<iframe src="https://player.vimeo.com/video/151207734?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  06. Graphing: One Variable at a Time**
<iframe src="https://player.vimeo.com/video/152493596?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  07. Graphing Relationships**
<iframe src="https://player.vimeo.com/video/160477834?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  08. Hypothesis Testing**
<iframe src="https://player.vimeo.com/video/133507581?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  09. Analysis of Variance**
<iframe src="https://player.vimeo.com/video/166245557?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  10. Chi-Square Test of Independence**
<iframe src="https://player.vimeo.com/video/172675181?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  11. Correlation**
<iframe src="https://player.vimeo.com/video/177164893?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  12. Moderation**
<iframe src="https://player.vimeo.com/video/179524400?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  13. The Question of Causation**
<iframe src="https://www.youtube.com/embed/Bg9eEcs9cVY?rel=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  14. Multivariate Models and Confounding**
<iframe src="https://player.vimeo.com/video/185704607?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Video:  15. Writing Your Poster Presentation**
<iframe src="https://player.vimeo.com/video/273462689?title=0&amp;byline=0&amp;portrait=0" width="747" height="420" frameborder="0" allowfullscreen="allowfullscreen"></iframe>


-->
